### ISSUE TITLE
Support for Python 2.7+?

### ISSUE THREAD

**Issue by pombredanne** [Photonios/pyasar#1]
It would be a nice addition!

**Comment by Photonios** [comment]
Feel free to add it. I exclusively use Python 3 for obvious reasons.

**Comment by pombredanne** [comment]
@Photonios what would be your `obvious` reasons, if you do not mind?

**Comment by Photonios** [comment]
Proper Unicode support to start with. Another one is AsyncIO. Also, the fact that `print` and `raise` are treated like functions. That just makes more sense.

**Comment by pombredanne** [comment]
You wrote:

> Proper Unicode support to start with. 

`from __future__ import unicode_literals` gets you that in Python 2

> Another one is AsyncIO.

tulip has been backported to Python2: See https://pypi.python.org/pypi/trollius

> Also, the fact that print and raise are treated like functions. That just makes more sense.

`from __future__ import print_function` gets you a print function. `raise` has never been a function in Python 3. 

And FWIW, you are using neither asyncio nor print and most handling bytes. That said, I apologize to bug you with this: you are not using any Python 3 feature from the look of it, so back porting will be easy.
